const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const DISCORD_TOKEN_SAMANTHA = process.env.DISCORD_TOKEN_SAMANTHA;
const DISCORD_DEPLOYMENT_CHANNEL = process.env.DISCORD_DEPLOYMENT_CHANNEL;

module.exports = {
  OPENAI_API_KEY,
  DISCORD_TOKEN_SAMANTHA,
  DISCORD_DEPLOYMENT_CHANNEL
};